#!/usr/bin/env bash
# install.sh — wire the rails-agents harness into a project repo.
#
# Usage: ./install.sh <target-repo> [<target-repo> ...]
#
# Portable: resolves this bundle's own location, so it works no matter where you
# cloned rails-agents. For each target it (re)creates the agent symlinks, wires the
# three hooks into the machine-local .claude/settings.local.json (gitignored — never
# committed, so a shared repo doesn't auto-run per-developer external scripts), and
# appends the harness .gitignore lines. Safe to re-run; preserves other keys.

set -euo pipefail

# Resolve this script's real directory, following symlinks.
src="${BASH_SOURCE[0]}"
while [ -h "$src" ]; do
  dir="$(cd -P "$(dirname "$src")" && pwd)"
  src="$(readlink "$src")"
  [[ $src != /* ]] && src="$dir/$src"
done
BUNDLE="$(cd -P "$(dirname "$src")" && pwd)"
GATE="$BUNDLE/reference/hooks/verification_gate.sh"
BANNER="$BUNDLE/reference/hooks/session_start_banner.sh"
PIPELINE="$BUNDLE/reference/hooks/pipeline_gate.sh"

[ -f "$GATE" ] || { echo "error: hook not found at $GATE — is this the rails-agents bundle?" >&2; exit 1; }
[ "$#" -ge 1 ] || { echo "usage: $0 <target-repo> [<target-repo> ...]" >&2; exit 1; }

# Prefer a $HOME-relative hook path so settings.local.json stays portable across a
# developer's own machines that clone the bundle to the same spot under home.
homerel() { case "$1" in "$HOME"/*) printf '$HOME/%s' "${1#"$HOME"/}";; *) printf '%s' "$1";; esac; }
gate_path="$(homerel "$GATE")"
banner_path="$(homerel "$BANNER")"
pipeline_path="$(homerel "$PIPELINE")"

wire_one() {
  local target="$1"
  [ -d "$target" ] || { echo "skip: $target is not a directory" >&2; return 1; }
  target="$(cd "$target" && pwd)"
  local cdir="$target/.claude"
  mkdir -p "$cdir/agents"

  # 1. agent symlinks -> this bundle. Link every bundle *.md except repo docs,
  #    then prune anything stale so agents/ mirrors the current bundle exactly
  #    (a removed agent must not leave a dangling link — the drift alarm's job).
  local -a want=()
  local n=0 kept=0
  for f in "$BUNDLE"/*.md; do
    local base; base="$(basename "$f")"
    # Skip bundle docs AND the bundle's own project instructions — none are agents.
    case "$base" in README.md | README-HANDOFF.md | QUICKSTART.md | CLAUDE.md) continue ;; esac
    # Never clobber a project-specific override committed as a real file: the repo's
    # own version (e.g. a customized rails-qa.md) wins over the bundle's.
    if [ -e "$cdir/agents/$base" ] && [ ! -L "$cdir/agents/$base" ]; then
      kept=$((kept + 1)); continue
    fi
    ln -sfn "$f" "$cdir/agents/$base"
    want+=("$base")
    n=$((n + 1))
  done
  [ "$kept" -gt 0 ] && echo "  agents: kept $kept committed project override(s)"
  # prune: drop any agents/ symlink that's broken or no longer in the bundle
  local pruned=0 l base keep
  for l in "$cdir/agents"/*; do
    [ -L "$l" ] || continue
    base="$(basename "$l")"
    keep=""
    for w in "${want[@]}"; do [ "$w" = "$base" ] && keep=1 && break; done
    if [ -z "$keep" ]; then rm -f "$l"; pruned=$((pruned + 1)); fi
  done
  [ "$pruned" -gt 0 ] && echo "  agents: pruned $pruned stale symlink(s)"

  # 1b. Ignore EXACTLY the machine-local bundle symlinks we manage, by name, in a
  #     per-dir .claude/agents/.gitignore — so committed project agents in the same
  #     directory stay tracked. Regenerated each run; other lines are preserved.
  python3 - "$cdir/agents/.gitignore" "${want[@]}" <<'PY'
import re, sys
p, names = sys.argv[1], sorted(sys.argv[2:])
BEGIN = "# >>> harness-managed: machine-local bundle agent symlinks (regenerated by install.sh; do not commit)"
END   = "# <<< harness-managed"
block = BEGIN + "\n" + "\n".join(names) + "\n" + END + "\n"
try:
    cur = open(p).read()
except FileNotFoundError:
    cur = ""
if BEGIN in cur and END in cur:
    cur = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", block, cur, flags=re.S)
else:
    cur = (cur.rstrip("\n") + "\n\n" if cur.strip() else "") + block
open(p, "w").write(cur)
print("  .claude/agents/.gitignore: managing %d bundle symlink(s)" % len(names))
PY

  # 2. settings.local.json — ensure all three hooks are present, preserving other keys.
  #    Hooks go in the machine-local, gitignored settings.local.json (NOT a committed
  #    settings.json): they run per-developer shell from $HOME/Development/rails-agents,
  #    so committing them to a shared repo would auto-execute unversioned external code on
  #    every teammate's checkout. Machine-local keeps the harness opt-in (each dev runs
  #    install.sh). Merges into an existing file, so re-running brings a repo to the full set.
  local settings="$cdir/settings.local.json"
  python3 - "$settings" "$banner_path" "$gate_path" "$pipeline_path" <<'PY'
import json, os, sys
p, banner, gate, pipeline = sys.argv[1:5]
s = json.load(open(p)) if os.path.exists(p) and os.path.getsize(p) > 0 else {}
h = s.setdefault("hooks", {})
def has(event, needle):
    return any(needle in hk.get("command", "") for grp in h.get(event, []) for hk in grp.get("hooks", []))
changed = []
if not has("SessionStart", "session_start_banner"):
    h.setdefault("SessionStart", []).append({"hooks": [{"type": "command", "command": f'bash "{banner}"'}]}); changed.append("SessionStart banner")
if not has("Stop", "verification_gate"):
    h.setdefault("Stop", []).append({"matcher": "", "hooks": [{"type": "command", "command": f'bash "{gate}"'}]}); changed.append("Stop gate")
if not has("PreToolUse", "pipeline_gate"):
    h.setdefault("PreToolUse", []).append({"matcher": "Edit|Write|MultiEdit|NotebookEdit", "hooks": [{"type": "command", "command": f'bash "{pipeline}"'}]}); changed.append("PreToolUse pipeline gate (warn)")
with open(p, "w") as f:
    json.dump(s, f, indent=2); f.write("\n")
print("  settings.local.json: " + ("added " + ", ".join(changed) if changed else "all hooks present"))
PY

  # 3. .gitignore harness block (session-local markers + machine-local settings).
  #    Agent symlinks are handled precisely by .claude/agents/.gitignore (step 1b),
  #    NOT by a blanket .claude/agents/ ignore — so committed project agents survive.
  local gi="$target/.gitignore"
  if grep -q "harness gitignore block" "$gi" 2>/dev/null; then
    echo "  .gitignore: harness block already present"
  else
    cat >> "$gi" <<'GI'

# harness gitignore block (managed by install.sh)
# Claude Code personal, machine-specific settings
.claude/settings.local.json

# Session-local harness markers (review + pipeline gate tokens)
.claude/.last-review
.claude/.current-story
.claude/.small-fix
.claude/.pipeline-block
GI
    echo "  .gitignore: harness block appended"
  fi

  echo "wired $target ($n agents -> $BUNDLE)"
}

for t in "$@"; do
  echo "==> $t"
  wire_one "$t"
done

echo
# One-time per machine: install a global ruleset into the ACTIVE config home
# (CLAUDE_CONFIG_DIR when set, e.g. a work profile; else ~/.claude).
cfg="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
if [ -f "$BUNDLE/templates/global-CLAUDE.md" ]; then
  echo "done. One-time per machine: cp \"$BUNDLE/templates/global-CLAUDE.md\" \"$cfg/CLAUDE.md\""
else
  echo "done. One-time per machine: put your global ruleset at \"$cfg/CLAUDE.md\" (see QUICKSTART.md)."
fi
