#!/usr/bin/env bash
# install.sh — wire the rails-agents harness into a project repo.
#
# Usage: ./install.sh <target-repo> [<target-repo> ...]
#
# Portable: resolves this bundle's own location, so it works no matter where you
# cloned rails-agents. For each target it (re)creates the agent symlinks, writes
# .claude/settings.json with the verification-gate Stop hook, and appends the
# harness .gitignore lines. Safe to re-run; never clobbers a settings.json that
# already defines other hooks.

set -euo pipefail

# Resolve this script's real directory, following symlinks.
src="${BASH_SOURCE[0]}"
while [ -h "$src" ]; do
  dir="$(cd -P "$(dirname "$src")" && pwd)"
  src="$(readlink "$src")"
  [[ $src != /* ]] && src="$dir/$src"
done
BUNDLE="$(cd -P "$(dirname "$src")" && pwd)"
GATE="$BUNDLE/reference/hooks/verification_gate.sh"
BANNER="$BUNDLE/reference/hooks/session_start_banner.sh"

[ -f "$GATE" ] || { echo "error: hook not found at $GATE — is this the rails-agents bundle?" >&2; exit 1; }
[ "$#" -ge 1 ] || { echo "usage: $0 <target-repo> [<target-repo> ...]" >&2; exit 1; }

# Prefer a $HOME-relative hook path so a committed settings.json stays portable
# across machines that clone the bundle to the same spot under home.
homerel() { case "$1" in "$HOME"/*) printf '$HOME/%s' "${1#"$HOME"/}";; *) printf '%s' "$1";; esac; }
gate_path="$(homerel "$GATE")"
banner_path="$(homerel "$BANNER")"

wire_one() {
  local target="$1"
  [ -d "$target" ] || { echo "skip: $target is not a directory" >&2; return 1; }
  target="$(cd "$target" && pwd)"
  local cdir="$target/.claude"
  mkdir -p "$cdir/agents"

  # 1. agent symlinks -> this bundle. Link every bundle *.md except repo docs,
  #    then prune anything stale so agents/ mirrors the current bundle exactly
  #    (a removed agent must not leave a dangling link — the drift alarm's job).
  local -a want=()
  local n=0
  for f in "$BUNDLE"/*.md; do
    local base; base="$(basename "$f")"
    case "$base" in README.md | README-HANDOFF.md | QUICKSTART.md) continue ;; esac
    ln -sfn "$f" "$cdir/agents/$base"
    want+=("$base")
    n=$((n + 1))
  done
  # prune: drop any agents/ symlink that's broken or no longer in the bundle
  local pruned=0 l base keep
  for l in "$cdir/agents"/*; do
    [ -L "$l" ] || continue
    base="$(basename "$l")"
    keep=""
    for w in "${want[@]}"; do [ "$w" = "$base" ] && keep=1 && break; done
    if [ -z "$keep" ]; then rm -f "$l"; pruned=$((pruned + 1)); fi
  done
  [ "$pruned" -gt 0 ] && echo "  agents: pruned $pruned stale symlink(s)"

  # 2. settings.json Stop hook — leave any pre-existing config alone
  local settings="$cdir/settings.json"
  if [ -f "$settings" ]; then
    if grep -q verification_gate "$settings"; then
      echo "  settings.json: already wired"
    else
      echo "  settings.json: exists without the gate — not clobbering; add manually:"
      echo "    SessionStart -> bash \"$banner_path\""
      echo "    Stop         -> bash \"$gate_path\""
    fi
  else
    local gate_cmd="bash \"$gate_path\"";     gate_cmd=${gate_cmd//\"/\\\"}
    local banner_cmd="bash \"$banner_path\""; banner_cmd=${banner_cmd//\"/\\\"}
    printf '{\n  "hooks": {\n    "SessionStart": [\n      {\n        "hooks": [\n          {\n            "type": "command",\n            "command": "%s"\n          }\n        ]\n      }\n    ],\n    "Stop": [\n      {\n        "matcher": "",\n        "hooks": [\n          {\n            "type": "command",\n            "command": "%s"\n          }\n        ]\n      }\n    ]\n  }\n}\n' "$banner_cmd" "$gate_cmd" > "$settings"
    echo "  settings.json: written (SessionStart banner + Stop gate)"
  fi

  # 3. .gitignore harness block (symlinks are machine-local build output)
  local gi="$target/.gitignore"
  if grep -q "harness roster" "$gi" 2>/dev/null; then
    echo "  .gitignore: harness block already present"
  else
    cat >> "$gi" <<'GI'

# Claude Code personal, machine-specific settings
.claude/settings.local.json

# Machine-local shared-agent symlinks (harness roster; regenerated by install.sh)
.claude/agents/
GI
    echo "  .gitignore: harness block appended"
  fi

  echo "wired $target ($n agents -> $BUNDLE)"
}

for t in "$@"; do
  echo "==> $t"
  wire_one "$t"
done

echo
echo "done. One-time per machine: cp \"$BUNDLE/templates/global-CLAUDE.md\" ~/.claude/CLAUDE.md"
