#!/usr/bin/env bash
# install.sh — wire the rails-agents harness into a project repo.
#
# Usage: ./install.sh <target-repo> [<target-repo> ...]
#
# Portable: resolves this bundle's own location, so it works no matter where you
# cloned rails-agents. For each target it (re)creates the agent symlinks, writes
# .claude/settings.json with the verification-gate Stop hook, and appends the
# harness .gitignore lines. Safe to re-run; never clobbers a settings.json that
# already defines other hooks.

set -euo pipefail

# Resolve this script's real directory, following symlinks.
src="${BASH_SOURCE[0]}"
while [ -h "$src" ]; do
  dir="$(cd -P "$(dirname "$src")" && pwd)"
  src="$(readlink "$src")"
  [[ $src != /* ]] && src="$dir/$src"
done
BUNDLE="$(cd -P "$(dirname "$src")" && pwd)"
GATE="$BUNDLE/reference/hooks/verification_gate.sh"
BANNER="$BUNDLE/reference/hooks/session_start_banner.sh"
PIPELINE="$BUNDLE/reference/hooks/pipeline_gate.sh"

[ -f "$GATE" ] || { echo "error: hook not found at $GATE — is this the rails-agents bundle?" >&2; exit 1; }
[ "$#" -ge 1 ] || { echo "usage: $0 <target-repo> [<target-repo> ...]" >&2; exit 1; }

# Prefer a $HOME-relative hook path so a committed settings.json stays portable
# across machines that clone the bundle to the same spot under home.
homerel() { case "$1" in "$HOME"/*) printf '$HOME/%s' "${1#"$HOME"/}";; *) printf '%s' "$1";; esac; }
gate_path="$(homerel "$GATE")"
banner_path="$(homerel "$BANNER")"
pipeline_path="$(homerel "$PIPELINE")"

wire_one() {
  local target="$1"
  [ -d "$target" ] || { echo "skip: $target is not a directory" >&2; return 1; }
  target="$(cd "$target" && pwd)"
  local cdir="$target/.claude"
  mkdir -p "$cdir/agents"

  # 1. agent symlinks -> this bundle. Link every bundle *.md except repo docs,
  #    then prune anything stale so agents/ mirrors the current bundle exactly
  #    (a removed agent must not leave a dangling link — the drift alarm's job).
  local -a want=()
  local n=0
  for f in "$BUNDLE"/*.md; do
    local base; base="$(basename "$f")"
    case "$base" in README.md | README-HANDOFF.md | QUICKSTART.md) continue ;; esac
    ln -sfn "$f" "$cdir/agents/$base"
    want+=("$base")
    n=$((n + 1))
  done
  # prune: drop any agents/ symlink that's broken or no longer in the bundle
  local pruned=0 l base keep
  for l in "$cdir/agents"/*; do
    [ -L "$l" ] || continue
    base="$(basename "$l")"
    keep=""
    for w in "${want[@]}"; do [ "$w" = "$base" ] && keep=1 && break; done
    if [ -z "$keep" ]; then rm -f "$l"; pruned=$((pruned + 1)); fi
  done
  [ "$pruned" -gt 0 ] && echo "  agents: pruned $pruned stale symlink(s)"

  # 2. settings.json — ensure all three hooks are present, preserving other keys.
  #    Merges into an existing settings.json (older installs, a custom model override)
  #    rather than skipping it, so re-running brings any repo to the full hook set.
  local settings="$cdir/settings.json"
  python3 - "$settings" "$banner_path" "$gate_path" "$pipeline_path" <<'PY'
import json, os, sys
p, banner, gate, pipeline = sys.argv[1:5]
s = json.load(open(p)) if os.path.exists(p) and os.path.getsize(p) > 0 else {}
h = s.setdefault("hooks", {})
def has(event, needle):
    return any(needle in hk.get("command", "") for grp in h.get(event, []) for hk in grp.get("hooks", []))
changed = []
if not has("SessionStart", "session_start_banner"):
    h.setdefault("SessionStart", []).append({"hooks": [{"type": "command", "command": f'bash "{banner}"'}]}); changed.append("SessionStart banner")
if not has("Stop", "verification_gate"):
    h.setdefault("Stop", []).append({"matcher": "", "hooks": [{"type": "command", "command": f'bash "{gate}"'}]}); changed.append("Stop gate")
if not has("PreToolUse", "pipeline_gate"):
    h.setdefault("PreToolUse", []).append({"matcher": "Edit|Write|MultiEdit|NotebookEdit", "hooks": [{"type": "command", "command": f'bash "{pipeline}"'}]}); changed.append("PreToolUse pipeline gate (warn)")
with open(p, "w") as f:
    json.dump(s, f, indent=2); f.write("\n")
print("  settings.json: " + ("added " + ", ".join(changed) if changed else "all hooks present"))
PY

  # 3. .gitignore harness block (symlinks are machine-local build output)
  local gi="$target/.gitignore"
  if grep -q "harness roster" "$gi" 2>/dev/null; then
    echo "  .gitignore: harness block already present"
  else
    cat >> "$gi" <<'GI'

# Claude Code personal, machine-specific settings
.claude/settings.local.json

# Machine-local shared-agent symlinks (harness roster; regenerated by install.sh)
.claude/agents/

# Session-local harness markers (review + pipeline gate tokens)
.claude/.last-review
.claude/.current-story
.claude/.small-fix
.claude/.pipeline-block
GI
    echo "  .gitignore: harness block appended"
  fi

  echo "wired $target ($n agents -> $BUNDLE)"
}

for t in "$@"; do
  echo "==> $t"
  wire_one "$t"
done

echo
echo "done. One-time per machine: cp \"$BUNDLE/templates/global-CLAUDE.md\" ~/.claude/CLAUDE.md"
